### ISSUE TITLE
Really appreciate this project. I have an idea

### ISSUE THREAD

**Issue by rnmp** [bugsnag/chromatic-sass#2]
Hey guys,

I found the article you posted about the project really enlightening, but I'm not sure if I want to install the plugin yet as I probably would only use it for a couple of gradients.

Because I think your project should be broadcasted more, I suggest you make an online tool to generate chromatic gradients (using your script) that outputs Sass code using the 5 RGB color stops. This way people can be exposed to the idea and be able to execute it right away.

Not to mention it's a great inbound marketing channel for your company.

That's all. My two cents.

**Comment by maxluster** [comment]
Hey! Appreciate the feedback. I am planning on making a demo page for the project similar to how you described. Hope you find it useful.
