### ISSUE TITLE
Question about the Tools in your Library

### ISSUE THREAD

**Issue by jhogue** [bugsnag/chromatic-sass#8]
Hello there, 

I came across your library when doing some research on color theory, SASS, and ways in which to convert RGB colors to LAB. Nice work here, looks very promising. I plan to download it and give it a try in a project. 

I was doing this research because I have a series of mixins and functions that I want to create to help solve a problem: 
1. Clients have brand colors that do not meet accessibility goals (Level AA most typically)
2. The HSB color space provides a way to adjust saturation and brightness to achieve a higher contrast without changing the Hue, which preserves the original intention of the color. Iit is imperfect, but it mostly works if the designer adjusts both values and judges what will pass vs. what preserves the original intent of the color. 
3. Making these adjustments is a manual process that a designer or a savvy developer needs to do, esp. when the client's brand "blue" might be used over white, light grey, or light blue. Each of these scenarios means tweaking the blue to pass contrast ratio checks. 
4. SASS can `darken()`, `lighten()`, `saturate()`, `scale-color()`, etc… but none of these do those things with the goal of hitting a target contrast ratio when compared to another color. 

I am interested in the latter… with lots of math and comparison checking, I'd like to create a mixin that can take two color values and adjusts the one foreground color value to pass an accessibility threshold, like so: `color: a11y-foreground($foreground, $background, $font-size: 16, $bold-or-not: false, $wcag-level: 'AA')`. 

I got pretty far but am stuck on how to calculate the distance between colors properly. That's why I was investigating LAB. Do you have any advice here, or any tools in the Chromatic library that could help achieve this? 

Thanks so much for any answer.

**Comment by tim-janik** [comment]
This module is just a wrapper around [chroma-js](https://www.npmjs.com/package/chroma-js), to make its functions available from sass.
So, for color distances, you might want to look at [chroma.distance](https://gka.github.io/chroma.js/#chroma-distance) from chroma-js.

**Comment by jhogue** [comment]
Thanks, I headed in that direction.
